class ItemCategory:
    UNKNOWN = 'Unknown'
    HELMET = 'Helmet'
    BODY_ARMOR = 'Body Armor'
    BELT = 'Belt'
    GLOVES = 'Gloves'
    BOOTS = 'Boots'
    WEAPON = 'Weapon'
    SHIELD = 'Shield'
    RING = 'Ring'
    AMULET = 'Amulet'
    JEWEL = 'Jewel'
    RUNE = 'Rune'
    CHARM = 'Charm'
